/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Chamith
 */
public class Home_Dashboard extends javax.swing.JFrame {

   private int x;
    private int y;
    
    public Home_Dashboard() {
        initComponents();
        
        
        
        Border user_border = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.white);
        lblUserRegistration.setBorder(user_border);
        lblUserReports.setBorder(user_border);
        lblViewBrands.setBorder(user_border);
        lblAddBrands.setBorder(user_border);
        lblAvailables.setBorder(user_border);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblUserRegistration = new javax.swing.JLabel();
        lblUserReports = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblViewBrands = new javax.swing.JLabel();
        lblAddBrands = new javax.swing.JLabel();
        lblLogOut = new javax.swing.JLabel();
        lblAvailables = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(Boolean.TRUE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo1.png"))); // NOI18N

        lblHome.setBackground(new java.awt.Color(255, 255, 255));
        lblHome.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 51, 51));
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/red.png"))); // NOI18N
        lblHome.setText("        Home");
        lblHome.setOpaque(true);

        lblUser.setBackground(new java.awt.Color(153, 153, 255));
        lblUser.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Manage User");
        lblUser.setOpaque(true);

        lblUserRegistration.setBackground(new java.awt.Color(204, 204, 255));
        lblUserRegistration.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblUserRegistration.setText("User Registration");
        lblUserRegistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUserRegistration.setOpaque(true);
        lblUserRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserRegistrationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUserRegistrationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUserRegistrationMouseExited(evt);
            }
        });

        lblUserReports.setBackground(new java.awt.Color(204, 204, 255));
        lblUserReports.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblUserReports.setText("View Users");
        lblUserReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUserReports.setOpaque(true);
        lblUserReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUserReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUserReportsMouseExited(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(153, 153, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Manage Brands");
        jLabel5.setOpaque(true);

        lblViewBrands.setBackground(new java.awt.Color(204, 204, 255));
        lblViewBrands.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblViewBrands.setText("View & Delete Brands");
        lblViewBrands.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblViewBrands.setOpaque(true);
        lblViewBrands.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewBrandsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewBrandsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewBrandsMouseExited(evt);
            }
        });

        lblAddBrands.setBackground(new java.awt.Color(204, 204, 255));
        lblAddBrands.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblAddBrands.setText("Add Brands");
        lblAddBrands.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAddBrands.setOpaque(true);
        lblAddBrands.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddBrandsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddBrandsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddBrandsMouseExited(evt);
            }
        });

        lblLogOut.setBackground(new java.awt.Color(153, 153, 255));
        lblLogOut.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        lblLogOut.setForeground(new java.awt.Color(255, 51, 51));
        lblLogOut.setText("Log Out");
        lblLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogOut.setOpaque(true);
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogOutMouseClicked(evt);
            }
        });

        lblAvailables.setBackground(new java.awt.Color(204, 204, 255));
        lblAvailables.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblAvailables.setText("Availables");
        lblAvailables.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAvailables.setOpaque(true);
        lblAvailables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAvailablesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAvailablesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAvailablesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewBrands, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUserRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUserReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddBrands, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAvailables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserReports, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblViewBrands, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddBrands, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvailables, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lblLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(255, 51, 51));
        btnClose.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("X");
        btnClose.setBorderPainted(false);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnMinimize.setBackground(new java.awt.Color(153, 153, 153));
        btnMinimize.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMinimize.setText("-");
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/home_32px.png"))); // NOI18N
        jLabel2.setText("Home");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 508, Short.MAX_VALUE)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClose)
                        .addComponent(btnMinimize)))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/STEP TO GO (1).png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblUserRegistrationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserRegistrationMouseEntered
        lblUserRegistration.setBackground(Color.white);
        lblUserRegistration.setForeground(Color.black);
    }//GEN-LAST:event_lblUserRegistrationMouseEntered

    private void lblUserRegistrationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserRegistrationMouseExited
        lblUserRegistration.setBackground(new Color(204,204,255));
        lblUserRegistration.setForeground(Color.black);
    }//GEN-LAST:event_lblUserRegistrationMouseExited

    private void lblUserReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserReportsMouseEntered
        lblUserReports.setBackground(Color.white);
        lblUserReports.setForeground(Color.black);
    }//GEN-LAST:event_lblUserReportsMouseEntered

    private void lblUserReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserReportsMouseExited
        lblUserReports.setBackground(new Color(204,204,255));
        lblUserReports.setForeground(Color.black);
    }//GEN-LAST:event_lblUserReportsMouseExited

    private void lblUserRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserRegistrationMouseClicked
        User_Register_Form form = new User_Register_Form();
        form.setVisible(true);
        form.pack();
        this.dispose();
    }//GEN-LAST:event_lblUserRegistrationMouseClicked

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        int opt = JOptionPane.showConfirmDialog(null, "Do you want to exit?","Exit",JOptionPane.YES_NO_OPTION);
        if (opt ==0 ) {
            dispose();
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        this.setExtendedState(User_Login_Form.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void lblViewBrandsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewBrandsMouseEntered
        lblViewBrands.setBackground(Color.white);
        lblViewBrands.setForeground(Color.black);
    }//GEN-LAST:event_lblViewBrandsMouseEntered

    private void lblViewBrandsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewBrandsMouseExited
        lblViewBrands.setBackground(new Color(204,204,255));
        lblViewBrands.setForeground(Color.black);
    }//GEN-LAST:event_lblViewBrandsMouseExited

    private void lblAddBrandsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddBrandsMouseEntered
        lblAddBrands.setBackground(Color.white);
        lblAddBrands.setForeground(Color.black);
    }//GEN-LAST:event_lblAddBrandsMouseEntered

    private void lblAddBrandsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddBrandsMouseExited
        lblAddBrands.setBackground(new Color(204,204,255));
        lblAddBrands.setForeground(Color.black);
    }//GEN-LAST:event_lblAddBrandsMouseExited

    private void lblLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseClicked
        int opt = JOptionPane.showConfirmDialog(null, "Do you want to exit?","Exit",JOptionPane.YES_NO_OPTION);
        if (opt == 0) {
            User_Login_Form form = new User_Login_Form();
            form.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_lblLogOutMouseClicked

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
       
      
    }//GEN-LAST:event_jPanel3MouseDragged

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
       
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        
    }//GEN-LAST:event_btnCloseMouseExited

    private void lblViewBrandsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewBrandsMouseClicked
        View_Brand_Form form = new View_Brand_Form();
        form.setVisible(true);
        form.pack();
        this.dispose();
    }//GEN-LAST:event_lblViewBrandsMouseClicked

    private void lblUserReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserReportsMouseClicked
        View_User_Form form = new View_User_Form();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblUserReportsMouseClicked

    private void lblAvailablesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvailablesMouseEntered
        lblAvailables.setBackground(Color.white);
        lblAvailables.setForeground(Color.black);
    }//GEN-LAST:event_lblAvailablesMouseEntered

    private void lblAvailablesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvailablesMouseExited
       lblAvailables.setBackground(new Color(204,204,255));
        lblAvailables.setForeground(Color.black);
    }//GEN-LAST:event_lblAvailablesMouseExited

    private void lblAvailablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvailablesMouseClicked
        Available_Form form = new Available_Form();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblAvailablesMouseClicked

    private void lblAddBrandsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddBrandsMouseClicked
        Add_Brand_Form form = new Add_Brand_Form();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblAddBrandsMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAddBrands;
    private javax.swing.JLabel lblAvailables;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserRegistration;
    private javax.swing.JLabel lblUserReports;
    private javax.swing.JLabel lblViewBrands;
    // End of variables declaration//GEN-END:variables
}
