/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import controller.ManageView;
import java.sql.*;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chamith
 */
public class View_User_Form extends javax.swing.JFrame {

    /**
     * Creates new form View_User_Form
     */
    public View_User_Form() {
        initComponents();
        
        Border user_border = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.white);
        jLabel_Register.setBorder(user_border);
        jLabel_Report.setBorder(user_border);
        lblViewBrands.setBorder(user_border);
        lblAddBrands.setBorder(user_border);
        lblAvailable.setBorder(user_border);
        
        tblUser.setSelectionBackground(new Color(204,204,204));
        tblUser.setSelectionForeground(Color.black);
        tblUser.setRowHeight(30);
        tblUser.setShowGrid(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_Home = new javax.swing.JLabel();
        jLabel_User = new javax.swing.JLabel();
        jLabel_Register = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblViewBrands = new javax.swing.JLabel();
        lblAddBrands = new javax.swing.JLabel();
        jLabel_Logout = new javax.swing.JLabel();
        jLabel_Report = new javax.swing.JLabel();
        lblAvailable = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnMinimize = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo1.png"))); // NOI18N

        jLabel_Home.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel_Home.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/red.png"))); // NOI18N
        jLabel_Home.setText("       Home");
        jLabel_Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_HomeMouseClicked(evt);
            }
        });

        jLabel_User.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_User.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel_User.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_User.setText("Manage User");
        jLabel_User.setOpaque(true);

        jLabel_Register.setBackground(new java.awt.Color(204, 204, 255));
        jLabel_Register.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_Register.setText("User Registration");
        jLabel_Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Register.setOpaque(true);
        jLabel_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_RegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_RegisterMouseExited(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(153, 153, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Manage Brands");
        jLabel5.setOpaque(true);

        lblViewBrands.setBackground(new java.awt.Color(204, 204, 255));
        lblViewBrands.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblViewBrands.setText("View & Delete Brands");
        lblViewBrands.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblViewBrands.setOpaque(true);
        lblViewBrands.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewBrandsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewBrandsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewBrandsMouseExited(evt);
            }
        });

        lblAddBrands.setBackground(new java.awt.Color(204, 204, 255));
        lblAddBrands.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblAddBrands.setText("Add Brands");
        lblAddBrands.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAddBrands.setOpaque(true);
        lblAddBrands.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddBrandsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddBrandsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddBrandsMouseExited(evt);
            }
        });

        jLabel_Logout.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_Logout.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel_Logout.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_Logout.setText("Log Out");
        jLabel_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Logout.setOpaque(true);

        jLabel_Report.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Report.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel_Report.setText("View Users");
        jLabel_Report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Report.setOpaque(true);
        jLabel_Report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_ReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ReportMouseExited(evt);
            }
        });

        lblAvailable.setBackground(new java.awt.Color(204, 204, 255));
        lblAvailable.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblAvailable.setText("Available");
        lblAvailable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAvailable.setOpaque(true);
        lblAvailable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAvailableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAvailableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAvailableMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_Logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Report, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddBrands, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblViewBrands, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_User, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Report, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblViewBrands, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddBrands, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        btnMinimize.setBackground(new java.awt.Color(204, 204, 204));
        btnMinimize.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMinimize.setText("-");
        btnMinimize.setBorderPainted(false);
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(255, 51, 51));
        btnClose.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("X");
        btnClose.setBorderPainted(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/user_24px new.png"))); // NOI18N
        jLabel1.setText("View Users");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClose)
                        .addComponent(btnMinimize)))
                .addGap(0, 39, Short.MAX_VALUE))
        );

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "E-mail", "Contact"
            }
        ));
        jScrollPane1.setViewportView(tblUser);

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton1.setText("VIEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_HomeMouseClicked
        Home_Dashboard form = new Home_Dashboard();
        form.setVisible(true);
        form.pack();
        this.dispose();
    }//GEN-LAST:event_jLabel_HomeMouseClicked

    private void jLabel_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegisterMouseClicked
        User_Register_Form form = new User_Register_Form();
        form.setVisible(true);
        form.pack();
        this.dispose();
    }//GEN-LAST:event_jLabel_RegisterMouseClicked

    private void jLabel_RegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegisterMouseEntered
        jLabel_Register.setBackground(Color.white);
        jLabel_Register.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_RegisterMouseEntered

    private void jLabel_RegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegisterMouseExited
        jLabel_Register.setBackground(new Color(204,204,255));
        jLabel_Register.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_RegisterMouseExited

    private void jLabel_ReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ReportMouseEntered
        
    }//GEN-LAST:event_jLabel_ReportMouseEntered

    private void jLabel_ReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ReportMouseExited
        
    }//GEN-LAST:event_jLabel_ReportMouseExited

    private void lblViewBrandsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewBrandsMouseClicked
        View_Brand_Form form = new View_Brand_Form();
        form.setVisible(true);
        form.pack();
        this.dispose();
    }//GEN-LAST:event_lblViewBrandsMouseClicked

    private void lblViewBrandsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewBrandsMouseEntered
        lblViewBrands.setBackground(Color.white);
        lblViewBrands.setForeground(Color.black);
    }//GEN-LAST:event_lblViewBrandsMouseEntered

    private void lblViewBrandsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewBrandsMouseExited
        lblViewBrands.setBackground(new Color(204,204,255));
        lblViewBrands.setForeground(Color.black);
    }//GEN-LAST:event_lblViewBrandsMouseExited

    private void lblAddBrandsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddBrandsMouseEntered
        lblAddBrands.setBackground(Color.white);
        lblAddBrands.setForeground(Color.black);
    }//GEN-LAST:event_lblAddBrandsMouseEntered

    private void lblAddBrandsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddBrandsMouseExited
        lblAddBrands.setBackground(new Color(204,204,255));
        lblAddBrands.setForeground(Color.black);
    }//GEN-LAST:event_lblAddBrandsMouseExited

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        this.setExtendedState(View_Brand_Form.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed

        Home_Dashboard form = new Home_Dashboard();
        form.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnCloseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            ManageView view = new ManageView();
            ResultSet rs = view.viewUsers();
            
            while (rs.next()) {                
                String Uname = String.valueOf(rs.getString("username"));
                String email = String.valueOf(rs.getString("email"));
                String contact = String.valueOf(rs.getString("contact"));

                String tbData[] = {Uname,email,contact};
                DefaultTableModel brandtable = (DefaultTableModel)tblUser.getModel();
                
                brandtable.addRow(tbData);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel brandtable = (DefaultTableModel)tblUser.getModel();
        brandtable.setRowCount(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lblAvailableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvailableMouseEntered
        lblAvailable.setBackground(Color.white);
        lblAvailable.setForeground(Color.black);
    }//GEN-LAST:event_lblAvailableMouseEntered

    private void lblAvailableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvailableMouseExited
       lblAvailable.setBackground(new Color(204,204,255));
        lblAvailable.setForeground(Color.black);
    }//GEN-LAST:event_lblAvailableMouseExited

    private void lblAvailableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvailableMouseClicked
       Available_Form form = new Available_Form();
       form.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lblAvailableMouseClicked

    private void lblAddBrandsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddBrandsMouseClicked
        Add_Brand_Form form = new Add_Brand_Form();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblAddBrandsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_User_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_User_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_User_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_User_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_User_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Home;
    private javax.swing.JLabel jLabel_Logout;
    private javax.swing.JLabel jLabel_Register;
    private javax.swing.JLabel jLabel_Report;
    private javax.swing.JLabel jLabel_User;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddBrands;
    private javax.swing.JLabel lblAvailable;
    private javax.swing.JLabel lblViewBrands;
    private javax.swing.JTable tblUser;
    // End of variables declaration//GEN-END:variables
}
